import React, { useState } from "react";
import { 
  ShieldCheck, 
  Info, 
  Ruler, 
  Cpu, 
  CheckSquare, 
  ScanFace, 
  FileText, 
  Compass, 
  Scale, 
  Tag, 
  ShoppingCart, 
  Volume2, 
  Languages 
} from "lucide-react";
import { DetectedObject } from "../types";
import { getApiUrl } from "../lib/api";

interface AnalysisPanelProps {
  scanResult: DetectedObject | null;
  isScanning: boolean;
}

export default function AnalysisPanel({ scanResult, isScanning }: AnalysisPanelProps) {
  const [prefLang, setPrefLang] = useState<"en" | "ar">("ar");
  const [isSpeaking, setIsSpeaking] = useState(false);
  const [translationInputText, setTranslationInputText] = useState("");
  const [customTranslation, setCustomTranslation] = useState("");
  const [translatingState, setTranslatingState] = useState(false);

  // Helper to safely format translation output, protecting against objects generated by Gemini
  const getTranslatedText = (): string => {
    if (!scanResult || !scanResult.translationResult) return "";
    const txt = scanResult.translationResult.translatedText;
    if (!txt) return "";
    if (typeof txt === "object" && txt !== null) {
      const obj = txt as Record<string, any>;
      const lines: string[] = [];
      if (obj.name) lines.push(`الاسم: ${obj.name}`);
      if (obj.category) lines.push(`الفئة: ${obj.category}`);
      if (obj.size) lines.push(`الحجم: ${obj.size}`);
      if (obj.weight) lines.push(`الوزن: ${obj.weight}`);
      if (obj.brand) lines.push(`الماركة: ${obj.brand}`);
      if (obj.summary) lines.push(`الملخص: ${obj.summary}`);
      for (const [key, val] of Object.entries(obj)) {
        if (!["name", "category", "size", "weight", "brand", "summary"].includes(key)) {
          lines.push(`${key}: ${val}`);
        }
      }
      return lines.join("\n");
    }
    return String(txt);
  };

  if (isScanning) {
    return (
      <div className="w-full bg-slate-900 border border-slate-800 rounded-2xl p-6 flex flex-col items-center justify-center min-h-[440px] gap-4 shadow-xl">
        <div className="relative w-20 h-20">
          <div className="absolute inset-0 rounded-full border-2 border-emerald-500 animate-ping opacity-75"></div>
          <div className="absolute inset-2 rounded-full border border-cyan-400 animate-pulse"></div>
          <div className="absolute inset-4 rounded-full bg-emerald-500/10 flex items-center justify-center">
            <ScanFace className="w-8 h-8 text-emerald-400 animate-bounce" />
          </div>
        </div>
        <div className="text-center">
          <p className="font-mono text-xs text-emerald-400 tracking-widest font-extrabold animate-pulse">
            SWEEPING ORNITHOLOGICAL & ELECTRONIC FREQUENCIES
          </p>
          <p className="text-[11px] text-slate-400 font-mono mt-2">
            استعلام خادم الذكاء الاصطناعي لفحص الهوية والوزن والماركة وبدائل الشراء...
          </p>
        </div>
      </div>
    );
  }

  if (!scanResult) {
    return (
      <div className="w-full bg-slate-900 border border-slate-800 rounded-2xl p-6 flex flex-col items-center justify-center min-h-[440px] gap-3 text-center shadow-xl">
        <div className="w-12 h-12 rounded-full bg-slate-950 flex items-center justify-center border border-slate-850 text-slate-500">
          <Compass className="w-6 h-6 animate-spin" style={{ animationDuration: '6s' }} />
        </div>
        <div>
          <h3 className="font-bold text-sm text-slate-200 uppercase">Telemetry Desk Empty</h3>
          <p className="text-xs text-slate-400 font-mono mt-1">منصة قراءة البيانات خالية</p>
          <p className="text-xs text-slate-500 mt-2.5 max-w-xs mx-auto">
            اختر أحد مقتنيات الأنيمي أو شاشات التلفاز وعناصر الغرفة والغذاء من الأسفل للتحليل الفوري، أو استخدم البث المباشر.
          </p>
        </div>
      </div>
    );
  }

  const isHighRisk = scanResult.hideCameraStatus.toLowerCase().includes("warning") ||
                     scanResult.hideCameraStatus.toLowerCase().includes("suspected");

  // Read telemetry with native browser speechSynthesis
  const triggerTextToSpeech = () => {
    if (isSpeaking) {
      window.speechSynthesis.cancel();
      setIsSpeaking(false);
      return;
    }

    const reportText = prefLang === "ar" && scanResult.translationResult
      ? `${getTranslatedText()}. نظام الحماية يفيد بـ: ${scanResult.hideCameraStatus}`
      : `${scanResult.name}. Category is ${scanResult.category}. Estimate weight is ${scanResult.weight || "unknown"}. Manufacturer brand is ${scanResult.brand || "unknown"}. Security check status is: ${scanResult.hideCameraStatus}`;

    const speech = new SpeechSynthesisUtterance(reportText);
    // Auto-detect voice language
    speech.lang = prefLang === "ar" ? "ar-XA" : "en-US";
    speech.rate = 0.95;

    speech.onend = () => setIsSpeaking(false);
    speech.onerror = () => setIsSpeaking(false);

    setIsSpeaking(true);
    window.speechSynthesis.speak(speech);
  };

  // Dedicated instant translation service
  const translateCustomSnippet = async (inputText: string) => {
    if (!inputText.trim()) return;
    setTranslatingState(true);

    const savedKey = localStorage.getItem("aiv_gemini_key") || "";
    const savedModel = localStorage.getItem("aiv_gemini_model") || "gemini-2.1-flash";
    const isOffline = localStorage.getItem("aiv_offline_mode") === "true";
    const savedLang = localStorage.getItem("aiv_target_lang") || "Arabic";

    // Map long-name language to short locale
    let targetLangCode = "ar";
    if (savedLang === "English") targetLangCode = "en";
    else if (savedLang === "Spanish") targetLangCode = "es";
    else if (savedLang === "French") targetLangCode = "fr";
    else if (savedLang === "Russian") targetLangCode = "ru";

    const savedEmail = localStorage.getItem("gemini_user_email") || "";
    const isAuthed = localStorage.getItem("gemini_secure_authed") === "true";

    try {
      const response = await fetch(getApiUrl("/api/translate"), {
        method: "POST",
        headers: { 
          "Content-Type": "application/json",
          "x-gemini-key": savedKey,
          "x-gemini-model": savedModel,
          "x-use-offline": isOffline ? "true" : "false",
          "x-gemini-email": savedEmail,
          "x-gemini-authed": isAuthed ? "true" : "false"
        },
        body: JSON.stringify({ text: inputText, targetLang: targetLangCode })
      });
      if (response.ok) {
        const data = await response.json();
        setCustomTranslation(data.translatedText);
      }
    } catch (e) {
      console.error(e);
      setCustomTranslation("حدث خطأ في الاتصال بالخادم لترجمة هذا النص.");
    } finally {
      setTranslatingState(false);
    }
  };

  return (
    <div className="w-full bg-slate-900 border border-slate-800 rounded-2xl p-5 flex flex-col gap-5 shadow-xl">
      
      {/* Language tab Selector & Audio voice controls */}
      <div className="flex items-center justify-between bg-slate-950 p-1.5 rounded-lg border border-slate-850">
        <div className="flex items-center gap-1">
          <button
            onClick={() => setPrefLang("ar")}
            className={`text-[10px] sm:text-xs px-2.5 py-1 rounded transition font-bold font-mono ${
              prefLang === "ar" ? "bg-emerald-600 text-slate-950 shadow" : "text-slate-400 hover:text-slate-200"
            }`}
          >
            العربية (arabic)
          </button>
          <button
            onClick={() => setPrefLang("en")}
            className={`text-[10px] sm:text-xs px-2.5 py-1 rounded transition font-bold font-mono ${
              prefLang === "en" ? "bg-emerald-600 text-slate-950 shadow" : "text-slate-400 hover:text-slate-200"
            }`}
          >
            English Specs
          </button>
        </div>

        {/* Speech audio synth trigger */}
        <button
          onClick={triggerTextToSpeech}
          className={`px-2.5 py-1 rounded text-[10px] font-bold font-mono flex items-center gap-1.5 transition ${
            isSpeaking 
              ? "bg-red-600/30 text-red-300 border border-red-500 animate-pulse" 
              : "bg-slate-850 hover:bg-slate-800 text-emerald-400 border border-slate-800"
          }`}
        >
          <Volume2 className="w-3.5 h-3.5" />
          {isSpeaking ? "إيقاف الصوت" : "قارئ التقرير"}
        </button>
      </div>

      {/* Target Title Block */}
      <div className="flex justify-between items-start border-b border-slate-800 pb-3 gap-2">
        <div className="text-right w-full flex flex-col items-stretch">
          {prefLang === "ar" ? (
            <div className="text-right">
              <span className="text-[9px] bg-emerald-500/10 text-emerald-400 px-2 py-0.5 rounded font-extrabold font-mono tracking-wider border border-emerald-500/20">
                الفئة: {scanResult.category === "Anime & Collectibles" ? "مقتنيات وفنون" :
                        scanResult.category === "TV & Room Equipment" ? "أجهزة وتلفزيونات" :
                        scanResult.category === "Objects & Tools" ? "أدوات ومجسمات" :
                        scanResult.category === "Animals & Creatures" ? "حيوان ومخلوقات" : "بشر تواصل وتفاعل"}
              </span>
              <h2 className="text-base sm:text-lg font-extrabold text-slate-100 mt-1.5 leading-snug">
                {scanResult.translationResult?.translatedText ? scanResult.name : scanResult.name}
              </h2>
              <p className="text-[9px] text-slate-400 font-mono mt-1">
                وقت الرصد: {new Date(scanResult.scannedAt).toLocaleTimeString()} // المصدر: {scanResult.source === "local_db" ? "قاعدة البيانات المحلية" : "مستكشف شبكة الويب والذكاء الاصطناعي"}
              </p>
            </div>
          ) : (
            <div className="text-left">
              <span className="text-[10px] bg-cyan-500/10 text-cyan-400 px-2.5 py-0.5 rounded font-bold font-mono tracking-wider border border-cyan-500/20">
                {scanResult.category.toUpperCase()}
              </span>
              <h2 className="text-base sm:text-lg font-black text-slate-200 tracking-tight mt-1">
                {scanResult.name}
              </h2>
              <p className="text-[10px] text-slate-400 font-mono mt-0.5">
                IDENTIFIED AT: {new Date(scanResult.scannedAt).toLocaleTimeString()} // SOURCE: {scanResult.source.toUpperCase()}
              </p>
            </div>
          )}
        </div>

        {/* Confidence Circle */}
        <div className="flex flex-col items-center flex-shrink-0 bg-slate-950 p-2 rounded-lg border border-slate-850">
          <span className="text-sm sm:text-base font-black font-mono text-emerald-400 leading-none">
            {scanResult.confidence}%
          </span>
          <span className="text-[8px] text-slate-500 font-bold tracking-widest mt-1">CONFIDENCE</span>
        </div>
      </div>

      {/* Multi-feature specifications sheet */}
      <div className="grid grid-cols-2 gap-2.5">
        
        {/* Dimensions/Size */}
        <div className="bg-slate-950/80 p-2 px-3 rounded-lg border border-slate-850 flex items-center gap-2">
          <Ruler className="w-3.5 h-3.5 text-emerald-400 flex-shrink-0" />
          <div className="overflow-hidden text-right sm:text-left flex-1">
            <p className="text-[8px] sm:text-[9px] text-slate-500 font-bold font-mono">
              {prefLang === "ar" ? "الأبعاد التقديرية" : "EST. SIZE"}
            </p>
            <p className="text-xs text-slate-200 font-mono font-bold truncate">{scanResult.size}</p>
          </div>
        </div>

        {/* Estimated Weight */}
        <div className="bg-slate-950/80 p-2 px-3 rounded-lg border border-slate-850 flex items-center gap-2">
          <Scale className="w-3.5 h-3.5 text-emerald-400 flex-shrink-0" />
          <div className="overflow-hidden text-right sm:text-left flex-1">
            <p className="text-[8px] sm:text-[9px] text-slate-500 font-bold font-mono">
              {prefLang === "ar" ? "الوزن التقديري" : "EST. WEIGHT"}
            </p>
            <p className="text-xs text-slate-200 font-mono font-bold truncate">
              {scanResult.weight || (prefLang === "ar" ? "غير متوفر" : "N/A")}
            </p>
          </div>
        </div>

        {/* Brand / Model Manufacturer */}
        <div className="bg-slate-950/80 p-2 px-3 rounded-lg border border-slate-850 flex items-center gap-2">
          <Tag className="w-3.5 h-3.5 text-emerald-400 flex-shrink-0" />
          <div className="overflow-hidden text-right sm:text-left flex-1">
            <p className="text-[8px] sm:text-[9px] text-slate-500 font-bold font-mono">
              {prefLang === "ar" ? "الشركة / الماركة" : "BRAND BRAND"}
            </p>
            <p className="text-xs text-slate-200 font-mono font-bold truncate">
              {scanResult.brand || (prefLang === "ar" ? "معيار عام" : "Generic")}
            </p>
          </div>
        </div>

        {/* Price Tag */}
        <div className="bg-slate-950/80 p-2 px-3 rounded-lg border border-slate-850 flex items-center gap-2">
          <ShoppingCart className="w-3.5 h-3.5 text-emerald-400 flex-shrink-0" />
          <div className="overflow-hidden text-right sm:text-left flex-1">
            <p className="text-[8px] sm:text-[9px] text-slate-500 font-bold font-mono">
              {prefLang === "ar" ? "السعر التقريبي" : "PRICE SCALE"}
            </p>
            <p className="text-xs text-amber-400 font-mono font-bold truncate">
              {scanResult.estimatedPrice || (prefLang === "ar" ? "فحص الويب" : "Web Check")}
            </p>
          </div>
        </div>
      </div>

      {/* Target Buy links & Retail shopping links */}
      {scanResult.buyLink && (
        <a
          href={scanResult.buyLink}
          target="_blank"
          rel="noopener noreferrer"
          className="flex items-center justify-center gap-2 bg-gradient-to-r from-amber-500 to-amber-600 text-slate-950 py-2.5 px-3 rounded-lg text-[11px] sm:text-xs font-bold leading-normal transition hover:from-amber-400 hover:to-amber-500 shadow-md transform active:scale-95"
        >
          <ShoppingCart className="w-4 h-4" />
          {prefLang === "ar" ? "ابحث عن المنتج للتسوق والشراء الآن" : "SEARCH PRODUCT ON GOOGLE SHOPPING"}
        </a>
      )}

      {/* Hidden spy camera surveillance scan alert */}
      <div className={`p-4 rounded-xl border ${
        isHighRisk
          ? "bg-red-950/20 border-red-500/40 text-red-200 animate-pulse"
          : "bg-emerald-950/15 border-emerald-500/30 text-slate-200"
      }`}>
        <h4 className="text-xs font-bold font-mono tracking-wider flex items-center gap-2">
          <ShieldCheck className={`w-4 h-4 ${isHighRisk ? "text-red-400 animate-pulse" : "text-emerald-400"}`} />
          {prefLang === "ar" ? "مكافحة التجسس والامتثال لسلامة الخصوصية" : "STEALTH & PRIVACY ANTI-SPY AUDIT"}
        </h4>
        <p className="text-xs text-slate-300 mt-1 leading-relaxed text-right sm:text-left">
          {prefLang === "ar" ? `فحص التوافق الأمني: تم الفحص الطيفي للمجسم والتحقق من الترددات الخانقة. ${scanResult.hideCameraStatus === "Threat Checked: Matte resin coating blocks optic reflection. Cavity inspection confirms 100% safe physical integrity." ? "هيكل معتم صلب آمن بالكامل ولا يحتوي على أي وسائط بث عشوائي." : scanResult.hideCameraStatus}` : scanResult.hideCameraStatus}
        </p>
      </div>

      {/* Dynamic Arabic / English summary translated presentation */}
      <div className="bg-slate-950/50 p-4 rounded-lg border border-slate-850">
        <h4 className="text-xs font-bold font-mono text-slate-400 flex items-center gap-1.5 mb-2">
          <FileText className="w-3.5 h-3.5 text-emerald-400" />
          {prefLang === "ar" ? "تقرير الفحص الطيفي والتحليل الفني للمواصفات" : "TECHNICAL SPECIFICATIONS ANALYSIS SUMMARY"}
        </h4>

        {prefLang === "ar" && scanResult.translationResult ? (
          <div className="text-xs text-slate-200 leading-relaxed text-right font-sans whitespace-pre-line space-y-1 bg-emerald-950/15 p-2 rounded border border-emerald-800/25">
            <p className="font-extrabold text-emerald-400 mb-1">{prefLang === "ar" ? "الملخص العربي المعتمد:" : "Approved Arabic translation:"}</p>
            <p>{getTranslatedText()}</p>
          </div>
        ) : (
          <p className="text-xs text-slate-300 leading-relaxed whitespace-pre-line">
            {scanResult.description}
          </p>
        )}
      </div>

      {/* Structured roots sub-infrastructure checklist */}
      {scanResult.toolsFound && scanResult.toolsFound.length > 0 && (
        <div>
          <h4 className="text-xs font-bold font-mono text-slate-400 flex items-center gap-1.5 mb-1.5">
            <CheckSquare className="w-3.5 h-3.5 text-emerald-400" />
            {prefLang === "ar" ? "العناصر والمكونات الهيكلية التي تم رصدها" : "IDENTIFIED VISUAL ELEMENT BOUNDS"}
          </h4>
          <div className="grid grid-cols-1 select-none gap-1.5">
            {scanResult.toolsFound.map((tool, idx) => (
              <div key={idx} className="flex items-center justify-between gap-2 bg-slate-950/80 px-3 py-1.5 rounded-lg border border-slate-850 text-right">
                <span className="text-xs text-slate-300 font-mono font-medium truncate order-2">{tool}</span>
                <div className="w-1.5 h-1.5 rounded-full bg-emerald-400 flex-shrink-0 animate-pulse order-1"></div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Dynamic instant text translation interface - "يرجم نصوص ومحادثات" */}
      <div className="bg-slate-950 p-3.5 rounded-xl border border-slate-800 flex flex-col gap-3">
        <h4 className="text-xs font-bold font-mono text-slate-300 flex items-center gap-1.5">
          <Languages className="w-4 h-4 text-emerald-400" />
          {prefLang === "ar" ? "أداة ترجمة فورية حية للنصوص والمحادثات" : "REAL-TIME SPEECH & TEXT TRANSLATOR"}
        </h4>
        <div className="flex gap-2">
          <input
            type="text"
            placeholder={prefLang === "ar" ? "اكتب أو الصق نصاً، محادثة شاشة، موديل لترجمته فوراً للعربية..." : "Type custom text, speech notes, screen labels to translate..."}
            value={translationInputText}
            onChange={(e) => setTranslationInputText(e.target.value)}
            className="flex-1 bg-slate-900 border border-slate-800 rounded px-2.5 py-1.5 text-xs text-slate-100 placeholder-slate-500 focus:outline-none focus:border-emerald-500/50"
          />
          <button
            onClick={() => translateCustomSnippet(translationInputText)}
            disabled={translatingState || !translationInputText}
            className="px-3 bg-emerald-600 hover:bg-emerald-500 disabled:bg-slate-800 font-bold font-mono text-slate-950 text-xs rounded transition flex-shrink-0"
          >
            {translatingState ? "..." : (prefLang === "ar" ? "ترجم" : "Translate")}
          </button>
        </div>
        {customTranslation && (
          <div className="bg-slate-900 p-2.5 rounded border border-slate-850 text-right text-xs text-emerald-400 font-sans leading-relaxed">
            <span className="text-[10px] text-slate-500 block mb-0.5">الترجمة الفورية المحققة:</span>
            {customTranslation}
          </div>
        )}
      </div>

    </div>
  );
}
